### ISSUE TITLE
[debug] It seems like MQTT works, but is not activating the AC

### ISSUE THREAD

**Issue by guysoft** [giladger/ElectraWifi#9]
Hey,

Is there a way to figure out what is not working on the AC side?

I built the board as shown in the instructions and flashed firmware.bin, but it seems like sending messages does not activate the AC.
Send over mqtt at ``devices/ac/state/json/set`` for example does get received:
```json
{"power": "on", "mode": "heat", "fan": "med", "temperature": 24, "ifeel": "off"}
```
And I can see that ``devices/ac/temperature/state`` gets updated with the correct temprature. However the AC does not power on.

Attaching the message broker output just to confirm the esp8266 communication works
![Screenshot_20220116_003520](https://user-images.githubusercontent.com/325670/149639929-3de7ade3-8054-4178-a4e3-772c54816954.png)

**Comment by giladger** [comment]
@guysoft Feel free to message me on https://www.facebook.com/giladger/ and I'll try to assist
